planning_plugins:
  - ompl_interface/OMPLPlanner

request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision

response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath

arm_r:
  default_planner_config: PTP
  longest_valid_segment_fraction: 0.01
  simplify_solutions: true
  projection_evaluator: joints(arm_r_joint1,arm_r_joint2)
  planner_configs:
    RRTConnect:
      type: geometric::RRTConnect
      range: 0.2
    RRTstar:
      type: geometric::RRTstar
      range: 0.2
    LBKPIECE:
      type: geometric::LBKPIECE
      range: 0.2

arm_l:
  default_planner_config: PTP
  longest_valid_segment_fraction: 0.01
  simplify_solutions: true
  projection_evaluator: joints(arm_l_joint1,arm_l_joint2)
  planner_configs:
    RRTConnect:
      type: geometric::RRTConnect
      range: 0.2
    RRTstar:
      type: geometric::RRTstar
      range: 0.2
    LBKPIECE:
      type: geometric::LBKPIECE
      range: 0.2